sudo: required
services:
  - docker

before_install:
  - docker build -t rgederin/fib-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rgederin/fib-client-test npm test -- --coverage

after_success:
  - docker build -t rgederin/fib-client -f ./client
  - docker build -t rgederin/fib-server -f ./server
  - docker build -t rgederin/fib-worker -f ./worker
  - docker build -t rgederin/fib-nginx -f ./nginx
