version: "3"
services:
  postgress:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: postgress
  redis:
    image: "redis:latest"
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
